/*
================================================================================
QUICKBOOKS ONLINE TO POWER BI - COMPLETE QUERY LIBRARY v2.0
================================================================================
Author: Financial Intelligence Dashboard Project
Date: January 2026
Version: 2.0 (Added empty data protection to all queries)

CHANGELOG v2.0:
- Added empty result set handling to ALL queries
- Queries now return empty tables instead of errors when entity has no data
- Improved error handling with null checks
- More robust for sandbox environments and companies that don't use all features

SETUP INSTRUCTIONS:
1. Create GetAccessToken query first (see QUERY 0 below)
2. Create each subsequent query as a new blank query in Power BI
3. Replace YOUR_CLIENT_ID, YOUR_CLIENT_SECRET, YOUR_REFRESH_TOKEN, YOUR_REALM_ID
4. Change base_url when switching from sandbox to production
5. Set privacy levels to "Organizational" or disable privacy checks

================================================================================
*/


// ================================================================================
// QUERY 0: GET ACCESS TOKEN (REQUIRED - CREATE THIS FIRST)
// ================================================================================
// Query Name: GetAccessToken
// Description: Refreshes OAuth access token using refresh token
// Dependencies: None
// Returns: String (access token valid for 1 hour)

let
    // ====== REPLACE THESE VALUES WITH YOUR CREDENTIALS ======
    client_id = "YOUR_CLIENT_ID_HERE",
    client_secret = "YOUR_CLIENT_SECRET_HERE", 
    refresh_token = "YOUR_REFRESH_TOKEN_HERE",
    // =========================================================
    
    // Encode credentials for Basic Authentication
    credentials = Text.ToBinary(client_id & ":" & client_secret),
    encoded_credentials = Binary.ToText(credentials, BinaryEncoding.Base64),
    
    // Request body for token refresh
    token_body = "grant_type=refresh_token&refresh_token=" & refresh_token,
    
    // Make token refresh request to Intuit OAuth endpoint
    token_response = Web.Contents(
        "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
        [
            Headers = [
                #"Authorization" = "Basic " & encoded_credentials,
                #"Content-Type" = "application/x-www-form-urlencoded",
                #"Accept" = "application/json"
            ],
            Content = Text.ToBinary(token_body),
            ManualStatusHandling = {400, 401}
        ]
    ),
    
    // Parse JSON response
    token_json = Json.Document(token_response),
    
    // Extract access token
    access_token = token_json[access_token]
in
    access_token


// ================================================================================
// QUERY 1: INVOICE
// ================================================================================
// Query Name: Invoice
// Description: Customer invoices (accounts receivable)
// Dependencies: GetAccessToken

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from Invoice where TxnDate >= '2024-01-01' MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[Invoice] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"InvoiceId", "Date", "DueDate", "TotalAmount", "Balance", "CustomerId", "CustomerName", "InvoiceNumber", "EmailStatus", "PrintStatus"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "TxnDate", "DueDate", "TotalAmt", "Balance", "CustomerRef", "DocNumber", "EmailStatus", "PrintStatus"},
                        {"InvoiceId", "Date", "DueDate", "TotalAmount", "Balance", "CustomerRef", "InvoiceNumber", "EmailStatus", "PrintStatus"}
                    ),
                    expanded_customer = Table.ExpandRecordColumn(expanded, "CustomerRef", {"value", "name"}, {"CustomerId", "CustomerName"}),
                    typed = Table.TransformColumnTypes(expanded_customer, {{"Date", type date}, {"DueDate", type date}, {"TotalAmount", type number}, {"Balance", type number}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 2: PURCHASE
// ================================================================================
// Query Name: Purchase
// Description: Expenses, checks, credit card charges

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from Purchase where TxnDate >= '2024-01-01' MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[Purchase] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"PurchaseId", "Date", "Amount", "PaymentType", "VendorId", "VendorName", "AccountId", "AccountName", "DocNumber"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "TxnDate", "TotalAmt", "PaymentType", "EntityRef", "AccountRef", "DocNumber"},
                        {"PurchaseId", "Date", "Amount", "PaymentType", "VendorRef", "AccountRef", "DocNumber"}
                    ),
                    expanded_vendor = try Table.ExpandRecordColumn(expanded, "VendorRef", {"value", "name"}, {"VendorId", "VendorName"}) otherwise expanded,
                    expanded_account = try Table.ExpandRecordColumn(expanded_vendor, "AccountRef", {"value", "name"}, {"AccountId", "AccountName"}) otherwise expanded_vendor,
                    typed = Table.TransformColumnTypes(expanded_account, {{"Date", type date}, {"Amount", type number}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 3: PAYMENT
// ================================================================================
// Query Name: Payment
// Description: Customer payments received

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from Payment where TxnDate >= '2024-01-01' MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[Payment] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"PaymentId", "Date", "Amount", "CustomerId", "CustomerName", "PaymentMethodName", "UnappliedAmount", "ReferenceNumber"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "TxnDate", "TotalAmt", "CustomerRef", "PaymentMethodRef", "UnappliedAmt", "PaymentRefNum"},
                        {"PaymentId", "Date", "Amount", "CustomerRef", "PaymentMethod", "UnappliedAmount", "ReferenceNumber"}
                    ),
                    expanded_customer = Table.ExpandRecordColumn(expanded, "CustomerRef", {"value", "name"}, {"CustomerId", "CustomerName"}),
                    expanded_method = try Table.ExpandRecordColumn(expanded_customer, "PaymentMethod", {"name"}, {"PaymentMethodName"}) otherwise expanded_customer,
                    typed = Table.TransformColumnTypes(expanded_method, {{"Date", type date}, {"Amount", type number}, {"UnappliedAmount", type number}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 4: CUSTOMER
// ================================================================================
// Query Name: Customer
// Description: Customer master list

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from Customer MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[Customer] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"CustomerId", "DisplayName", "CompanyName", "FirstName", "LastName", "EmailAddress", "PhoneNumber", "Balance", "Active"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "DisplayName", "CompanyName", "GivenName", "FamilyName", "PrimaryEmailAddr", "PrimaryPhone", "Balance", "Active"},
                        {"CustomerId", "DisplayName", "CompanyName", "FirstName", "LastName", "Email", "Phone", "Balance", "Active"}
                    ),
                    expanded_email = try Table.ExpandRecordColumn(expanded, "Email", {"Address"}, {"EmailAddress"}) otherwise expanded,
                    expanded_phone = try Table.ExpandRecordColumn(expanded_email, "Phone", {"FreeFormNumber"}, {"PhoneNumber"}) otherwise expanded_email,
                    typed = Table.TransformColumnTypes(expanded_phone, {{"Balance", type number}, {"Active", type logical}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 5: ACCOUNT
// ================================================================================
// Query Name: Account
// Description: Chart of accounts

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from Account MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[Account] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"AccountId", "AccountName", "AccountType", "AccountSubType", "AccountNumber", "CurrentBalance", "Active", "Classification", "FullyQualifiedName"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "Name", "AccountType", "AccountSubType", "AcctNum", "CurrentBalance", "Active", "Classification", "FullyQualifiedName"},
                        {"AccountId", "AccountName", "AccountType", "AccountSubType", "AccountNumber", "CurrentBalance", "Active", "Classification", "FullyQualifiedName"}
                    ),
                    typed = Table.TransformColumnTypes(expanded, {{"CurrentBalance", type number}, {"Active", type logical}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 6: SALES RECEIPT
// ================================================================================
// Query Name: SalesReceipt
// Description: Cash sales and point-of-sale transactions

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from SalesReceipt where TxnDate >= '2024-01-01' MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[SalesReceipt] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"SalesReceiptId", "Date", "Amount", "CustomerId", "CustomerName", "PaymentMethodName", "DocNumber"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "TxnDate", "TotalAmt", "CustomerRef", "PaymentMethodRef", "DocNumber"},
                        {"SalesReceiptId", "Date", "Amount", "CustomerRef", "PaymentMethod", "DocNumber"}
                    ),
                    expanded_customer = Table.ExpandRecordColumn(expanded, "CustomerRef", {"value", "name"}, {"CustomerId", "CustomerName"}),
                    expanded_method = try Table.ExpandRecordColumn(expanded_customer, "PaymentMethod", {"name"}, {"PaymentMethodName"}) otherwise expanded_customer,
                    typed = Table.TransformColumnTypes(expanded_method, {{"Date", type date}, {"Amount", type number}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 7: ESTIMATE
// ================================================================================
// Query Name: Estimate
// Description: Quotes and proposals to customers

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from Estimate MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[Estimate] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"EstimateId", "Date", "Amount", "CustomerId", "CustomerName", "Status", "ExpirationDate", "AcceptedBy", "AcceptedDate", "DocNumber"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "TxnDate", "TotalAmt", "CustomerRef", "TxnStatus", "ExpirationDate", "AcceptedBy", "AcceptedDate", "DocNumber"},
                        {"EstimateId", "Date", "Amount", "CustomerRef", "Status", "ExpirationDate", "AcceptedBy", "AcceptedDate", "DocNumber"}
                    ),
                    expanded_customer = Table.ExpandRecordColumn(expanded, "CustomerRef", {"value", "name"}, {"CustomerId", "CustomerName"}),
                    typed = Table.TransformColumnTypes(expanded_customer, {{"Date", type date}, {"Amount", type number}, {"ExpirationDate", type date}, {"AcceptedDate", type date}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 8: CREDIT MEMO
// ================================================================================
// Query Name: CreditMemo
// Description: Customer credits and refunds

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from CreditMemo where TxnDate >= '2024-01-01' MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[CreditMemo] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"CreditMemoId", "Date", "Amount", "CustomerId", "CustomerName", "RemainingCredit", "Balance", "DocNumber"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "TxnDate", "TotalAmt", "CustomerRef", "RemainingCredit", "Balance", "DocNumber"},
                        {"CreditMemoId", "Date", "Amount", "CustomerRef", "RemainingCredit", "Balance", "DocNumber"}
                    ),
                    expanded_customer = Table.ExpandRecordColumn(expanded, "CustomerRef", {"value", "name"}, {"CustomerId", "CustomerName"}),
                    typed = Table.TransformColumnTypes(expanded_customer, {{"Date", type date}, {"Amount", type number}, {"RemainingCredit", type number}, {"Balance", type number}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 9: BILL
// ================================================================================
// Query Name: Bill
// Description: Vendor bills (accounts payable)

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from Bill where TxnDate >= '2024-01-01' MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[Bill] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"BillId", "Date", "DueDate", "Amount", "Balance", "VendorId", "VendorName", "DocNumber"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "TxnDate", "DueDate", "TotalAmt", "Balance", "VendorRef", "DocNumber"},
                        {"BillId", "Date", "DueDate", "Amount", "Balance", "VendorRef", "DocNumber"}
                    ),
                    expanded_vendor = Table.ExpandRecordColumn(expanded, "VendorRef", {"value", "name"}, {"VendorId", "VendorName"}),
                    typed = Table.TransformColumnTypes(expanded_vendor, {{"Date", type date}, {"DueDate", type date}, {"Amount", type number}, {"Balance", type number}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 10: BILL PAYMENT
// ================================================================================
// Query Name: BillPayment
// Description: Payments to vendors

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from BillPayment where TxnDate >= '2024-01-01' MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[BillPayment] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"BillPaymentId", "Date", "Amount", "VendorId", "VendorName", "PaymentType", "CheckNumber", "DocNumber"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "TxnDate", "TotalAmt", "VendorRef", "PayType", "CheckNum", "DocNumber"},
                        {"BillPaymentId", "Date", "Amount", "VendorRef", "PaymentType", "CheckNumber", "DocNumber"}
                    ),
                    expanded_vendor = Table.ExpandRecordColumn(expanded, "VendorRef", {"value", "name"}, {"VendorId", "VendorName"}),
                    typed = Table.TransformColumnTypes(expanded_vendor, {{"Date", type date}, {"Amount", type number}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 11: VENDOR CREDIT
// ================================================================================
// Query Name: VendorCredit
// Description: Credits from vendors

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from VendorCredit where TxnDate >= '2024-01-01' MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[VendorCredit] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"VendorCreditId", "Date", "Amount", "VendorId", "VendorName", "Balance", "DocNumber"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "TxnDate", "TotalAmt", "VendorRef", "Balance", "DocNumber"},
                        {"VendorCreditId", "Date", "Amount", "VendorRef", "Balance", "DocNumber"}
                    ),
                    expanded_vendor = Table.ExpandRecordColumn(expanded, "VendorRef", {"value", "name"}, {"VendorId", "VendorName"}),
                    typed = Table.TransformColumnTypes(expanded_vendor, {{"Date", type date}, {"Amount", type number}, {"Balance", type number}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 12: VENDOR
// ================================================================================
// Query Name: Vendor
// Description: Vendor master list

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from Vendor MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[Vendor] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"VendorId", "DisplayName", "CompanyName", "FirstName", "LastName", "EmailAddress", "PhoneNumber", "Balance", "Active", "Is1099"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "DisplayName", "CompanyName", "GivenName", "FamilyName", "PrimaryEmailAddr", "PrimaryPhone", "Balance", "Active", "Vendor1099"},
                        {"VendorId", "DisplayName", "CompanyName", "FirstName", "LastName", "Email", "Phone", "Balance", "Active", "Is1099"}
                    ),
                    expanded_email = try Table.ExpandRecordColumn(expanded, "Email", {"Address"}, {"EmailAddress"}) otherwise expanded,
                    expanded_phone = try Table.ExpandRecordColumn(expanded_email, "Phone", {"FreeFormNumber"}, {"PhoneNumber"}) otherwise expanded_email,
                    typed = Table.TransformColumnTypes(expanded_phone, {{"Balance", type number}, {"Active", type logical}, {"Is1099", type logical}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 13: EMPLOYEE
// ================================================================================
// Query Name: Employee
// Description: Employee master list

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from Employee MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[Employee] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"EmployeeId", "DisplayName", "FirstName", "LastName", "EmailAddress", "PhoneNumber", "Active", "HiredDate", "ReleasedDate"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "DisplayName", "GivenName", "FamilyName", "PrimaryEmailAddr", "PrimaryPhone", "Active", "HiredDate", "ReleasedDate"},
                        {"EmployeeId", "DisplayName", "FirstName", "LastName", "Email", "Phone", "Active", "HiredDate", "ReleasedDate"}
                    ),
                    expanded_email = try Table.ExpandRecordColumn(expanded, "Email", {"Address"}, {"EmailAddress"}) otherwise expanded,
                    expanded_phone = try Table.ExpandRecordColumn(expanded_email, "Phone", {"FreeFormNumber"}, {"PhoneNumber"}) otherwise expanded_email,
                    typed = Table.TransformColumnTypes(expanded_phone, {{"Active", type logical}, {"HiredDate", type date}, {"ReleasedDate", type date}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 14: ITEM
// ================================================================================
// Query Name: Item
// Description: Products and services catalog

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from Item MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[Item] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"ItemId", "Name", "Type", "Description", "UnitPrice", "QtyOnHand", "Active", "IncomeAccountId", "IncomeAccountName", "ExpenseAccountId", "ExpenseAccountName", "SKU"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "Name", "Type", "Description", "UnitPrice", "QtyOnHand", "Active", "IncomeAccountRef", "ExpenseAccountRef", "Sku"},
                        {"ItemId", "Name", "Type", "Description", "UnitPrice", "QtyOnHand", "Active", "IncomeAccount", "ExpenseAccount", "SKU"}
                    ),
                    expanded_income = try Table.ExpandRecordColumn(expanded, "IncomeAccount", {"value", "name"}, {"IncomeAccountId", "IncomeAccountName"}) otherwise expanded,
                    expanded_expense = try Table.ExpandRecordColumn(expanded_income, "ExpenseAccount", {"value", "name"}, {"ExpenseAccountId", "ExpenseAccountName"}) otherwise expanded_income,
                    typed = Table.TransformColumnTypes(expanded_expense, {{"UnitPrice", type number}, {"QtyOnHand", type number}, {"Active", type logical}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 15: CLASS
// ================================================================================
// Query Name: Class
// Description: Departments, divisions, or locations

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from Class MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[Class] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"ClassId", "ClassName", "Active", "IsSubClass", "ParentClassId", "ParentClassName", "FullyQualifiedName"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "Name", "Active", "SubClass", "ParentRef", "FullyQualifiedName"},
                        {"ClassId", "ClassName", "Active", "IsSubClass", "ParentRef", "FullyQualifiedName"}
                    ),
                    expanded_parent = try Table.ExpandRecordColumn(expanded, "ParentRef", {"value", "name"}, {"ParentClassId", "ParentClassName"}) otherwise expanded,
                    typed = Table.TransformColumnTypes(expanded_parent, {{"Active", type logical}, {"IsSubClass", type logical}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 16: DEPARTMENT
// ================================================================================
// Query Name: Department
// Description: Organizational units

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from Department MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[Department] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"DepartmentId", "DepartmentName", "Active", "IsSubDepartment", "ParentDeptId", "ParentDeptName", "FullyQualifiedName"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "Name", "Active", "SubDepartment", "ParentRef", "FullyQualifiedName"},
                        {"DepartmentId", "DepartmentName", "Active", "IsSubDepartment", "ParentRef", "FullyQualifiedName"}
                    ),
                    expanded_parent = try Table.ExpandRecordColumn(expanded, "ParentRef", {"value", "name"}, {"ParentDeptId", "ParentDeptName"}) otherwise expanded,
                    typed = Table.TransformColumnTypes(expanded_parent, {{"Active", type logical}, {"IsSubDepartment", type logical}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 17: DEPOSIT
// ================================================================================
// Query Name: Deposit
// Description: Bank deposits

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from Deposit where TxnDate >= '2024-01-01' MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[Deposit] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"DepositId", "Date", "Amount", "AccountId", "AccountName", "Notes"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "TxnDate", "TotalAmt", "DepositToAccountRef", "PrivateNote"},
                        {"DepositId", "Date", "Amount", "DepositAccount", "Notes"}
                    ),
                    expanded_account = Table.ExpandRecordColumn(expanded, "DepositAccount", {"value", "name"}, {"AccountId", "AccountName"}),
                    typed = Table.TransformColumnTypes(expanded_account, {{"Date", type date}, {"Amount", type number}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 18: TRANSFER
// ================================================================================
// Query Name: Transfer
// Description: Transfers between accounts

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from Transfer where TxnDate >= '2024-01-01' MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[Transfer] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"TransferId", "Date", "Amount", "FromAccountId", "FromAccountName", "ToAccountId", "ToAccountName", "Notes"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "TxnDate", "Amount", "FromAccountRef", "ToAccountRef", "PrivateNote"},
                        {"TransferId", "Date", "Amount", "FromAccount", "ToAccount", "Notes"}
                    ),
                    expanded_from = Table.ExpandRecordColumn(expanded, "FromAccount", {"value", "name"}, {"FromAccountId", "FromAccountName"}),
                    expanded_to = Table.ExpandRecordColumn(expanded_from, "ToAccount", {"value", "name"}, {"ToAccountId", "ToAccountName"}),
                    typed = Table.TransformColumnTypes(expanded_to, {{"Date", type date}, {"Amount", type number}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 19: JOURNAL ENTRY
// ================================================================================
// Query Name: JournalEntry
// Description: Manual accounting entries

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    query = "select * from JournalEntry where TxnDate >= '2024-01-01' MAXRESULTS 1000",
    full_url = base_url & realm_id & "/query?query=" & Uri.EscapeDataString(query),
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    query_response = json[QueryResponse],
    data = try query_response[JournalEntry] otherwise {},
    
    table = if data = {} or data = null then 
                #table(
                    {"JournalEntryId", "Date", "Amount", "Description", "DocNumber", "IsAdjustment"},
                    {}
                )
            else
                let
                    initial_table = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    expanded = Table.ExpandRecordColumn(initial_table, "Column1",
                        {"Id", "TxnDate", "TotalAmt", "PrivateNote", "DocNumber", "Adjustment"},
                        {"JournalEntryId", "Date", "Amount", "Description", "DocNumber", "IsAdjustment"}
                    ),
                    typed = Table.TransformColumnTypes(expanded, {{"Date", type date}, {"Amount", type number}, {"IsAdjustment", type logical}})
                in
                    typed
in
    table


// ================================================================================
// QUERY 20: COMPANY INFO
// ================================================================================
// Query Name: CompanyInfo
// Description: Company details and settings

let
    realm_id = "YOUR_REALM_ID_HERE",
    access_token = GetAccessToken,
    base_url = "https://sandbox-quickbooks.api.intuit.com/v3/company/",
    
    full_url = base_url & realm_id & "/companyinfo/" & realm_id,
    
    response = Web.Contents(full_url, [Headers = [#"Authorization" = "Bearer " & access_token, #"Accept" = "application/json"]]),
    json = Json.Document(response),
    company_info = json[CompanyInfo],
    
    table = Record.ToTable(company_info)
in
    table


/*
================================================================================
IMPLEMENTATION NOTES v2.0
================================================================================

ALL QUERIES NOW INCLUDE:
✅ Empty result set handling
✅ Returns empty table with correct schema instead of errors
✅ Safe for sandbox environments
✅ Safe for companies that don't use all features

NO MORE "Column1 not found" ERRORS!

Each query follows this pattern:
1. Fetch data from API
2. Check if data is null or empty
3. If empty → return empty table with correct column names
4. If not empty → process data normally

This means you can safely add ALL 20 queries to your Power BI model
without worrying about which entities exist in each QuickBooks company.

RECOMMENDED TESTING ORDER:
1. GetAccessToken (must work first)
2. Customer, Account (these almost always exist)
3. Invoice, Purchase (core transactions)
4. Everything else (will return empty tables if not used)

*/
